<?php
/*
 * Base class as abstract
 */
abstract class SaurusMigration extends DynamicMigration {
  protected $arguments = array();
  public function __construct($arguments) {
    $this->arguments=$arguments;
    parent::__construct();

    $this->team = array(
      new MigrateTeamMember('Andy Kohv', 'andy@mekaia.com',
                            t('Programmer')),
    );
  }


  protected function generateMachineName($class_name = NULL) {
    return $this->arguments['machine_name'];
  }
  //Check if the date is a valid unix timestamp
  public function check_date($value) {
    if(strtotime($value)<0){
      return 0;
    }else{
      return $value;
    };
  }
}
